services:
  identityservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:IdentityConnectionString=Server=identitydb;Database=IdentityDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=True;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8094:8080"
    depends_on:
    - identitydb   
    - rabbitmq 

  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "8090:1433"
    environment:
      - SA_PASSWORD=MATF12345678rs2
      - ACCEPT_EULA=Y

  post.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:mssql=Server=mssql;Database=PostDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=True;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8080:8080"
    depends_on:
      - mssql
      - rabbitmq 

  mssql:
    container_name: mssql
    restart: always
    ports:
      - "8091:1433"
    environment:
      - SA_PASSWORD=MATF12345678rs2
      - ACCEPT_EULA=Y
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672 


