services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
  post.api:
    image: ${DOCKER_REGISTRY-}postapi
    build:
      context: .
      dockerfile: Services/Post/Post.API/Dockerfile
