services:
  mssql:
    container_name: mssql
    restart: always
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=MATF12345678rs2
      - ACCEPT_EULA=Y
  post.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:mssql=Server=mssql;Database=PostDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=True;Encrypt=False;"
    ports:
      - "8080:8080"
    depends_on:
      - mssql