services:
  identityservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:IdentityConnectionString=Server=identitydb;Database=IdentityDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=True;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8094:8080"
    depends_on:
    - identitydb
    - rabbitmq

  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "8090:1433"
    environment:
      - SA_PASSWORD=MATF12345678rs2
      - ACCEPT_EULA=Y

  post.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:mssql=Server=mssql;Database=PostDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=True;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "GrpcSettings:RelationsUrl=http://relations.grpc:8080"
    ports:
      - "8080:8080"
    depends_on:
      - mssql
      - rabbitmq
      - relations.grpc

  mssql:
    container_name: mssql
    restart: always
    ports:
      - "8091:1433"
    environment:
      - SA_PASSWORD=MATF12345678rs2
      - ACCEPT_EULA=Y

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  relationsdb:
    container_name: relationsdb
    hostname: relationsdb
    restart: always
    ports:
     - "7474:7474"
     - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/12345678
    volumes:
      - neo4j_data:\data

  relations.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "Neo4jSettings:ConnectionString=neo4j://relationsdb:7687"
      - "Neo4jSettings:Username=neo4j"
      - "Neo4jSettings:Password=12345678"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8000:8080"
    depends_on:
      - relationsdb
      - rabbitmq

  relations.grpc:
    container_name: relations.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Neo4jSettings:ConnectionString=neo4j://relationsdb:7687"
      - "Neo4jSettings:Username=neo4j"
      - "Neo4jSettings:Password=12345678"
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - relationsdb
    ports:
      - "8003:8080"


  chat.api:
    container_name: chat.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8095:8080"

