services:

  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile
    volumes:
      - app_logs:/app/logs

  identitydb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest

  post.api:
    image: ${DOCKER_REGISTRY-}postapi
    build:
      context: .
      dockerfile: Services/Post/Post.API/Dockerfile
    volumes:
      - app_logs:/app/logs

  rabbitmq:
    image: rabbitmq:3-management-alpine

  relationsdb:
    image: neo4j
  relations.api:
    image: ${DOCKER_REGISTRY-}relationsapi
    build:
      context: .
      dockerfile: Services/Relations/Relations.API/Dockerfile
    volumes:
      - app_logs:/app/logs

  relations.grpc:
    image: relations.grpc
    build:
      context: .
      dockerfile: Services/Relations/Relations.GRPC/Dockerfile


  chat.api:
    image: ${DOCKER_REGISTRY-}chatapi
    build:
      context: .
      dockerfile: Services/Chat/Chat.API/Dockerfile
    volumes:
      - app_logs:/app/logs

  chatdb:
    image: mcr.microsoft.com/mssql/server:2022-latest



volumes:
    neo4j_data:
    post_uploads:
    identity_uploads:
    app_logs:



